/**
 * attach directives to this module
 * if you get 'unknown {x}Provider' errors from angular, be sure they are
 * properly referenced in one of the module dependencies in the array.
 **/
define([
    './join',
    './onFinishRender',
    './objectSelect',
    './contextMenu',
    './resizable',
    './focus-on-show',
    './upload-border',
    './datadoc-pane',
    './datepicker',
    './ui-switch',
    './v-resizable',
    './on-render',
    './infinite-scroll',
    './vs-repeat',
    './fsm-sticky-header',
    './widget-container',
    './click-out',
    './viz-filters',
    './ingest-db-tables',
    // './viz-chart',
    './viz-list',
    './only-numeric',
    './limit-to',
    './collapsed-tags',
    './embed-widget',
    './embed-settings',
    './sort-settings-dropdown',
    './limit-settings-dropdown',
    './main-page-ds-pane',
    './main-page-file-details',
    './add-folder-pane',
    './sort-columns',
    './ng-select-items',
    './ng-touchend',
    './mobile-search',
    './compile',
    './datadoc-presence',
    './responsive-settings',
    './static-include',
    './ingest-other-settings-dropdown',
    './sticky-note',
    './format-toolbar',
    './search-settings-dropdown',
    './uploads',
    './query-editor'

], function () {});
